export const orderMocke = {
  orders: [
    {
      id: 68400971,
      uuid: '00000-606cab2b-bb4ad9',
      comment: null,
      device_id: null,
      remote_id: null,
      ref: 105,
      loyalty: 0,
      covers: 0,
      table: 0,
      id_restaurant: 2824,
      created_at: '2021-04-06T21:19:42+02:00',
      due_date: '2021-04-06T21:15:42+02:00',
      mode: 2,
      source: 3,
      status: 255,
      total_discount: 0,
      price: 5100,
      contents: [
        {
          id: 5165,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 151651165,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 651651,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 54565654,
          name: 'Sie Yai',
          type: 'dish',
          item_id: 515307,
          contents: [],
          price: 1350,
        },
        {
          id: 65651651,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 651615,
          name: 'Frais de livraison',
          type: 'dish',
          item_id: 527933,
          contents: [],
          price: 350,
        },
      ],
      channel: 'Web',
      virtual_brand_name: null,
      delivery_started: '2021-04-06T20:54:58+02:00',
      delivery_ended: '2021-04-06T22:32:41+02:00',
      delivery_address: {
        id: 4000663,
        remote_id: null,
        name: 'Addresse Web',
        street: 'Rue Neuve',
        street_num: '43',
        zip_code: '78490',
        city: 'Les Mesnuls',
        formatted_address: '43 Rue Neuve, 78490 Les Mesnuls, France',
        google_id: 'ChIJk6YslzCc5kcRQW0k9GVaBQk',
        location: null,
        address_more: '',
        floor: '',
        door: '',
        building: '',
        code: '',
      },
    },
    {
      id: 68405958,
      uuid: '00000-606cb322-d5836a',
      comment: 'Super commentaire',
      device_id: null,
      remote_id: null,
      ref: 104,
      loyalty: 0,
      covers: 0,
      table: 0,
      id_restaurant: 2824,
      created_at: '2021-04-06T21:14:50+02:00',
      due_date: '2021-04-06T21:15:42+02:00',
      mode: 2,
      source: 3,
      status: 255,
      total_discount: 0,
      price: 3900,
      contents: [
        {
          id: 242625401,
          name: 'La big Formule',
          type: 'menu',
          item_id: 19743,
          contents: [
            {
              id: 515303,
              type: 'dish',
              name: 'Le Tonton',
              contents: [],
            },
            {
              id: 515338,
              type: 'dish',
              name: 'Frites fraiches',
              contents: [
                {
                  id: 176810,
                  type: 'option_value',
                  quantity: 1,
                  name: 'Ketchup',
                },
              ],
            },
            {
              id: 515325,
              type: 'dish',
              name: 'Coca Cola',
              contents: [],
            },
            {
              id: 515334,
              type: 'dish',
              name: 'Tiramisu maison',
              contents: [],
            },
          ],
          price: 1750,
        },
        {
          id: 242625402,
          name: 'La big Formule',
          type: 'menu',
          item_id: 19743,
          contents: [
            {
              id: 515299,
              type: 'dish',
              name: 'Le Hubert',
              contents: [],
            },
            {
              id: 515338,
              type: 'dish',
              name: 'Frites fraiches',
              contents: [
                {
                  id: 176809,
                  type: 'option_value',
                  quantity: 1,
                  name: 'Mayonnaise',
                },
              ],
            },
            {
              id: 515327,
              type: 'dish',
              name: 'Sprite',
              contents: [],
            },
            {
              id: 515331,
              type: 'dish',
              name: 'Brownie',
              contents: [],
            },
          ],
          price: 1800,
        },
        {
          id: 242625403,
          name: 'Frais de livraison',
          type: 'dish',
          item_id: 527933,
          contents: [],
          price: 350,
        },
        {
          id: 12,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 13,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 14,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 15,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 16,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 17,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 18,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
      ],
      channel: 'Web',
      virtual_brand_name: null,
      delivery_started: null,
      delivery_ended: null,
      delivery_address: {
        id: 4000774,
        remote_id: null,
        name: 'Addresse Web',
        street: 'Rue Amaury',
        street_num: '4',
        zip_code: '78490',
        city: "Montfort-l'Amaury",
        formatted_address: "4 Rue Amaury, 78490 Montfort-l'Amaury, France",
        google_id: 'ChIJN98ZGLee5kcRKpH9-OcndAo',
        location: null,
        address_more:
          "Nous habitons au 4bis et non au 4 (numéro non disponible sur le site). L'interphone ne fonctionne pas. Merci d'appeler sur le téléphone en arrivant sur le téléphone ou bien sur Whats'App (merci d'avance, le réseau est défaillant à l'intérieur de notre maison)",
        floor: '',
        door: '',
        building: '',
        code: '',
      },
    },
    {
      id: 68400970,
      uuid: '00000-606caa2b-bb4ad9',
      comment: null,
      device_id: null,
      remote_id: null,
      ref: 103,
      loyalty: 0,
      covers: 0,
      table: 0,
      id_restaurant: 2824,
      created_at: '2021-04-06T20:36:27+02:00',
      due_date: '2021-04-06T21:15:43+02:00',
      mode: 2,
      source: 3,
      status: 255,
      total_discount: 0,
      price: 5100,
      contents: [
        {
          id: 242609417,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 242609419,
          name: 'Sie Yai',
          type: 'dish',
          item_id: 515307,
          contents: [],
          price: 1350,
        },
        {
          id: 242609417484,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 2426094194,
          name: 'Sie Yai',
          type: 'dish',
          item_id: 515307,
          contents: [],
          price: 1350,
        },
        {
          id: 242609420,
          name: 'Poke Saumon',
          type: 'dish',
          item_id: 515312,
          contents: [
            {
              id: 177405,
              type: 'option_value',
              quantity: 1,
              name: 'sauce soja sucré',
            },
          ],
          price: 1350,
        },
        {
          id: 242609421,
          name: 'Nems',
          type: 'dish',
          item_id: 515320,
          contents: [],
          price: 400,
        },
        {
          id: 242609422,
          name: 'Nems',
          type: 'dish',
          item_id: 515320,
          contents: [],
          price: 400,
        },
        {
          id: 242609423,
          name: 'Frais de livraison',
          type: 'dish',
          item_id: 527933,
          contents: [],
          price: 350,
        },
      ],
      channel: 'Web',
      virtual_brand_name: null,
      delivery_started: '2021-04-06T20:54:58+02:00',
      delivery_ended: '2021-04-06T22:32:41+02:00',
      delivery_address: {
        id: 4000663,
        remote_id: null,
        name: 'Addresse Web',
        street: 'Rue Neuve',
        street_num: '43',
        zip_code: '78490',
        city: 'Les Mesnuls',
        formatted_address: '43 Rue Neuve, 78490 Les Mesnuls, France',
        google_id: 'ChIJk6YslzCc5kcRQW0k9GVaBQk',
        location: null,
        address_more: '',
        floor: '',
        door: '',
        building: '',
        code: '',
      },
    },
    {
      id: 68400953,
      uuid: '00000-606caa05-b6a810',
      comment: null,
      device_id: null,
      remote_id: null,
      ref: 102,
      loyalty: 0,
      covers: 0,
      table: 0,
      id_restaurant: 2824,
      created_at: '2021-04-06T20:35:49+02:00',
      due_date: '2021-04-06T21:15:44+02:00',
      mode: 2,
      source: 3,
      status: 255,
      total_discount: 0,
      price: 6650,
      contents: [
        {
          id: 242609356,
          name: 'Veggie Lover',
          type: 'dish',
          item_id: 515314,
          contents: [
            {
              id: 177405,
              type: 'option_value',
              quantity: 1,
              name: 'sauce soja sucré',
            },
          ],
          price: 1200,
        },
        {
          id: 24260935754545,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 242609357875,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 24260935795,
          name: 'Le Nervous Breakdown',
          type: 'dish',
          item_id: 515301,
          contents: [],
          price: 1300,
        },
        {
          id: 242609360,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 24260941745,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 242609418,
          name: 'Red Curry (relevé)',
          type: 'dish',
          item_id: 515309,
          contents: [],
          price: 1250,
        },
        {
          id: 242609361,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 242609360,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 2426093695,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 242609363,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 24260936495,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 242609365,
          name: 'Le Mexicain',
          type: 'dish',
          item_id: 515305,
          contents: [],
          price: 1250,
        },
        {
          id: 242609364,
          name: 'Pad Thaï',
          type: 'dish',
          item_id: 515306,
          contents: [],
          price: 1300,
        },
        {
          id: 242609366,
          name: 'Frais de livraison',
          type: 'dish',
          item_id: 527933,
          contents: [],
          price: 350,
        },
      ],
      channel: 'Web',
      virtual_brand_name: null,
      delivery_started: '2021-04-06T20:54:07+02:00',
      delivery_ended: '2021-04-06T22:33:48+02:00',
      delivery_address: {
        id: 4000642,
        remote_id: null,
        name: 'Addresse Web',
        street: 'Rue de la Mairie',
        street_num: '14',
        zip_code: '78490',
        city: 'Galluis',
        formatted_address: '14 Rue de la Mairie, 78490 Galluis, France',
        google_id:
          'EioxNCBSdWUgZGUgbGEgTWFpcmllLCA3ODQ5MCBHYWxsdWlzLCBGcmFuY2UiGhIYChQKEglB1QJpMJnmRxH_Qg8Y_TdD8hAO',
        location: null,
        address_more: '',
        floor: '',
        door: '',
        building: '',
        code: '',
      },
    },
    // {
    //   id: 68400914,
    //   uuid: '00000-606caa02-c5d51d',
    //   comment: null,
    //   device_id: null,
    //   remote_id: null,
    //   ref: 101,
    //   loyalty: 0,
    //   covers: 0,
    //   table: 0,
    //   id_restaurant: 2824,
    //   created_at: '2021-04-06T20:35:46+02:00',
    //   due_date: '2021-04-06T21:15:45+02:00',
    //   mode: 2,
    //   source: 3,
    //   status: 255,
    //   total_discount: 500,
    //   price: 3250,
    //   contents: [
    //     {
    //       id: 242609218,
    //       name: 'Pad Thaï',
    //       type: 'dish',
    //       item_id: 515306,
    //       contents: [],
    //       price: 1300,
    //     },
    //     {
    //       id: 242609220,
    //       name: 'Poke Saumon',
    //       type: 'dish',
    //       item_id: 515312,
    //       contents: [
    //         {
    //           id: 177405,
    //           type: 'option_value',
    //           quantity: 1,
    //           name: 'sauce soja sucré',
    //         },
    //       ],
    //       price: 1350,
    //     },
    //     {
    //       id: 242609221,
    //       name: 'Tiramisu maison',
    //       type: 'dish',
    //       item_id: 515334,
    //       contents: [],
    //       price: 350,
    //     },
    //     {
    //       id: 242609222,
    //       name: 'Frites fraiches',
    //       type: 'dish',
    //       item_id: 515338,
    //       contents: [
    //         {
    //           id: 176809,
    //           type: 'option_value',
    //           quantity: 1,
    //           name: 'Mayonnaise',
    //         },
    //       ],
    //       price: 400,
    //     },
    //     {
    //       id: 242609223,
    //       name: 'Frais de livraison',
    //       type: 'dish',
    //       item_id: 527933,
    //       contents: [],
    //       price: 350,
    //     },
    //   ],
    //   channel: 'Web',
    //   virtual_brand_name: null,
    //   delivery_started: '2021-04-06T20:57:55+02:00',
    //   delivery_ended: '2021-04-06T21:28:42+02:00',
    //   delivery_address: {
    //     id: 3997974,
    //     remote_id: null,
    //     name: 'Addresse Web',
    //     street: "Place de l'Écu",
    //     street_num: '3',
    //     zip_code: '78770',
    //     city: 'Thoiry',
    //     formatted_address: "3 Place de l'Écu, 78770 Thoiry, France",
    //     google_id: 'ChIJNZxtFtaZ5kcRdevvz9fRg7c',
    //     location: null,
    //     address_more: 'interphone : Boumansour',
    //     floor: '1',
    //     door: '1',
    //     building: '',
    //     code: '',
    //   },
    //   coupon_id: 1212311,
    //   coupon_code: '5-hub',
    // },
  ],
  errno: 0,
};
